YoureDone/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('foodlog/', include('foodlog.urls')),
    path('admin/', admin.site.urls),
]

foodlog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'foodlog'
urlpatterns = [
	path('users/', views.users, name='users'),
    path('index/', views.index, name='index'),
    path('<int:foodlist_id>/', views.detail, name='detail'),
    path('delete/<int:pk>/', views.foodlist_delete, name='foodlist_delete'),
    path('<int:foodlist_id>/<int:food_id>/', views.food_delete, name='food_delete')
]

foodlog/models.py
from django.db import models
from datetime import date
from django.utils import timezone
from django.contrib.auth.models import User

class Food(models.Model):
    foodlist = models.ForeignKey('Foodlist', default=0, on_delete=models.CASCADE)
    food_text = models.CharField(max_length=20,default='NA')
    calories = models.IntegerField(default=0)
    def __str__(self):
        return self.food_text
class Foodlist(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE) # id 2 is admin
    eat_date = models.DateField('Date Eaten',default=date.today)
    def __str__(self):
        return str(self.eat_date)
    def was_published_recently(self):
        return self.eat_date >= timezone.now() - datetime.timedelta(days=1)
class SearchedFood(models.Model):
    food_text = models.CharField(max_length=20,default='NA')
    calories = models.IntegerField(default=0)
#class Users(models.User)

foodlog/forms.py
from django import forms

class newfoodForm(forms.Form):
    newFood = forms.CharField(label='New food', max_length=100)
    newCalories = forms.IntegerField(label="New food's calories", min_value=0, max_value=99999)
class newlogForm(forms.Form):
	newLog = forms.DateField(label='New date')#, max_length=100)
class searchdatabaseForm(forms.Form):
	databaseSearch = forms.CharField(label='Search field', max_length=100)

foodlog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from .models import Foodlist, Food, SearchedFood
from usda.client import UsdaClient
from decouple import config
from .forms import newfoodForm,newlogForm,searchdatabaseForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
import requests


API_KEY = config('API_KEY')
client = UsdaClient(API_KEY)

#Log in/Create A User
def users(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        form2 = AuthenticationForm(request.POST)
        nextForm = newlogForm()
        if 'signup' in request.POST:
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=raw_password)
            
        else:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            #return redirect('/foodlog/index/')
        if user is not None:
            latest_foodlists = user.foodlist_set.all().order_by('-eat_date')
            totalCalories = []
            
            for foodlist in latest_foodlists:
                total = 0
                for foods in foodlist.food_set.all():
                    total+=foods.calories
                totalCalories.append(total)

            latest_foodlists = zip(latest_foodlists, totalCalories)
            login(request, user)
            context = {
                'form': nextForm, 'latest_foodlists': latest_foodlists
            }
            return render(request, 'foodlog/index.html', context)
    else:
        form = UserCreationForm()
        form2 = AuthenticationForm()
    return render(request, 'foodlog/users.html', {'form': form, 'form2':form2})

#User's list of logs
def index(request):
    user = get_object_or_404(User, pk=request.user.id)
    latest_foodlists = user.foodlist_set.all().order_by('-eat_date')
    totalCalories = []

    for foodlist in latest_foodlists:
        total = 0
        for foods in foodlist.food_set.all():
            total+=foods.calories
        totalCalories.append(total)

    latest_foodlists = zip(latest_foodlists, totalCalories)
    if request.method == 'POST':
        if 'add' in request.POST:
            form = newlogForm
            q = Foodlist(user = user)
            q.save()
        else:
            form = newlogForm(request.POST)
            if form.is_valid():
                q = Foodlist(eat_date=form.cleaned_data['newLog'], user = user)
                q.save()
    else:
        form = newlogForm()

    context = {
        'latest_foodlists': latest_foodlists, 'form': form
    }

    return render(request, 'foodlog/index.html', context)

#List of a log's food. Contains search food feature.
def detail(request, foodlist_id):
    foodlist = get_object_or_404(Foodlist, pk=foodlist_id)
    foods = []
    foodResults = []    
    if request.method == 'POST':
        if 'insert' in request.POST:
            form = newfoodForm(request.POST)
            form2 = searchdatabaseForm()
            if form.is_valid():
                foodlist.food_set.create(food_text=form.cleaned_data['newFood'], calories=form.cleaned_data['newCalories'])
                foodlist.save()
                print(request.POST)

#Search field     

        elif 'search' in request.POST:
            form = newfoodForm()
            form2 = searchdatabaseForm(request.POST)
            if form2.is_valid():
                searchtext = form2.cleaned_data['databaseSearch']
                foods_search = client.search_foods(searchtext, 1500)
                for x in range(1500):
                    try:
                        foods.append(next(foods_search))
                    except:
                        break
                for x in range(len(foods)):
                    report = client.get_food_report(foods[x].id)
                    for nutrient in report.nutrients:
                        calories = 0
                        if nutrient.name == 'Energy':
                            foodResults.append(SearchedFood(food_text=foods[x].name, calories=nutrient.value))
                            break
                        elif nutrient.name == 'Protein':
                            calories += nutrient.value*4
                        elif nutrient.name == 'Total lipid (fat)':
                            calories += nutrient.value*9
                        elif nutrient.name == 'Carbohydrate, by difference':
                            calories += nutrient.value*4
                    foodResults.append(SearchedFood(food_text=foods[x].name, calories = calories))
#Add searched food button

        elif '+' in request.POST.values():            
            form = newfoodForm()
            form2 = searchdatabaseForm()
            pair = [key for key in request.POST.keys()][1].split("|")
            print(pair)
            foodlist.food_set.create(food_text=pair[0], calories=int(float(pair[1])))
            foodlist.save()
        else:
            form = newfoodForm()
            form2 = searchdatabaseForm()
            print(request.POST)
    else:
        form = newfoodForm()
        form2 = searchdatabaseForm()
    return render(request, 'foodlog/detail.html', {'foodlist': foodlist, 'form': form, 'form2': form2, 'foodResults': foodResults})

#Delete a foodlist
def foodlist_delete(request, pk):    
    foodlist = get_object_or_404(Foodlist, pk=pk)
    if request.method == 'POST':
        foodlist.delete()                  
        return redirect('/foodlog/index/')             

    return render(request, 'foodlog/index.html', {'foodlist': foodlist})

#Delete a food
def food_delete(request, foodlist_id,food_id):
    foodlist = get_object_or_404(Foodlist, pk=foodlist_id)    
    food = get_object_or_404(Food, pk=food_id)  

    if request.method == 'POST':         
        food.delete()                      

    return render(request, 'foodlog/detail.html', {'foodlist': foodlist})


foodlog/templates/foodlog/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'foodlog/style.css' %}">
<h1>here are the foods you ate on {{ foodlist.eat_date }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if foodlist.food_set.all %}

<table>

	<th>Food</th>
	<th>Calories</th>
	<th></th>

{% for food in foodlist.food_set.all %}
    <tr>

    	<td>{{ food.food_text}}</td>         
    	<td>{{ food.calories}}</td>   
    	<td>
    		<form action="{% url 'foodlog:food_delete' foodlist.id food.id%}" method="post">
    				{% csrf_token %}
    				<input type="submit" value="Delete entry">
			</form>
		</td>
	</tr>>
{% endfor %}

</table>
{% else %}

<p>This log has no food in it :(</p>

{% endif %}

<form action="{% url 'foodlog:detail' foodlist.id %}" method="post">
	{% csrf_token %}
    {{ form }}
    <input type="submit" name="insert" value="Submit">
</form>





<form action="{% url 'foodlog:detail' foodlist.id %}" method="post">
	{% csrf_token %}
    {{ form2 }}
    <input type="submit" name="search" value="Search">
</form>


{% if foodResults %}
<table>

	<th>Food</th>
	<th>Calories per 100 grams</th>
	<th></th>

{% for foods in foodResults %}
    <tr>

    <td>{{ foods.food_text }}</td>
    <td>{{ foods.calories }}</td>	
    <td> 
    	<form action="{% url 'foodlog:detail' foodlist.id %}" method="post">
    		{% csrf_token %}
    		<input type="submit" name="{{foods.food_text}}|{{foods.calories}}" value="+"> 
    	</form>
    </td>
    		
	</tr>>
{% endfor %}

</table>

{% endif %}

foodlog/templates/foodlog/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'foodlog/style.css' %}">
<h1>here are your foodlogs. you can create new logs at the bottom</h1>
{% if latest_foodlists %}
    

    <table>

    	<th>Date</th>
    	<th>Total Calories</th>
    	<th></th>

    
    {% for foodlist, totalCalories in latest_foodlists %}
	<tr>
        <td><a href="{% url 'foodlog:detail' foodlist.id %}">{{ foodlist.eat_date }}</a></td>

        <td>{{ totalCalories }}</td>

        <td>
        	<form action="{% url 'foodlog:foodlist_delete' foodlist.id %}" method="post">
    				{% csrf_token %}
    				<input type="submit" value="Delete entry">
			</form>		
		</td>
     </tr>   
    {% endfor %}
	

    </table>
    
{% else %}
    <p>No logs are available :(</p>

{% endif %}

<form action="/foodlog/index/" method="post">
    		{% csrf_token %}
    		<input type = "submit" name = "add" value = "Add">
    </form>


<form action="/foodlog/index/" method="post">
    	{% csrf_token %}
    	{{ form }}
    	<input type="submit" value="Submit">
	</form>

foodlog/templates/foodlog/users.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'foodlog/style.css' %}">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
<h1>sign up or log in to create a foodlog entry :)</h1>

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Sign up')">Sign up</button>
  <button class="tablinks" onclick="openTab(event, 'Log in')">Log in</button>
</div>

<div id="Sign up" class="tabcontent">
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" name="signup">Sign up</button>
  </form>
</div>

<div id="Log in" class="tabcontent">
  <form method="post">
    {% csrf_token %}
    {% for field in form2 %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" name="login">Log in</button>
  </form>
</div>


<script>
function openTab(evt, tabName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>
   
</body>
</html> 
